// @ts-ignore `.open-next/worker.js` is generated by the OpenNext build.
import handler from "./.open-next/worker.js"

import { getFaxSessionIdFromRequest } from "./src/server/session/fax-session-request.service"
import { isWebSocketUpgradeRequest } from "./src/shared/websocket/is-websocket-upgrade-request"

// Wrangler must see the Durable Object class exported from the deployed Worker.
export { FaxSession } from "./src/server/session/fax-session.durable-object"
export { FaxPollingCoordinator } from "./src/server/fax/fax-polling-coordinator.durable-object"
export { FaxDeliveryWorkflow } from "./src/server/fax/fax-delivery.workflow"

/**
 * This custom Worker is the public entry point for the entire application.
 * OpenNext handles normal Next.js requests, but WebSocket upgrade requests need
 * to be intercepted here and explicitly routed to a Durable Object.
 */
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)

    // A WebSocket starts as an HTTP request asking to upgrade its connection.
    // Both checks matter: the path selects our session-events endpoint, while
    // the header distinguishes a socket handshake from an ordinary HTTP call.
    if (
      url.pathname === "/api/session/events" &&
      isWebSocketUpgradeRequest(request)
    ) {
      return connectFaxSessionWebSocket(request, env)
    }

    // Everything unrelated to the session WebSocket continues through the
    // generated OpenNext Worker and into the appropriate Next.js route/page.
    return handler.fetch(request, env, ctx)
  },
} satisfies ExportedHandler<CloudflareEnv>

/**
 * Authenticates the WebSocket handshake and forwards it to the Durable Object
 * belonging to the browser's signed fax session.
 *
 * The browser does not put a session ID in the URL. Its signed session cookie
 * supplies that identity in the same way it does for the regular API routes.
 */
async function connectFaxSessionWebSocket(
  request: Request,
  env: CloudflareEnv
): Promise<Response> {
  const sessionId = await getFaxSessionIdFromRequest(
    request,
    env.SESSION_COOKIE_PASSWORD
  )

  if (!sessionId) {
    return new Response("Unauthorized", { status: 401 })
  }

  // getByName returns a reference to this session's Durable Object. Passing it
  // the original request lets that object complete the WebSocket upgrade and
  // keep the server side of the connection.
  return env.FAX_SESSIONS.getByName(sessionId).fetch(request)
}
