// @ts-ignore `.open-next/worker.js` is generated by the OpenNext build.
import handler from "./.open-next/worker.js"

export { FaxSession } from "./src/server/session/fax-session"

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>
