CREATE TABLE IF NOT EXISTS `fax_session` (
	`id` integer PRIMARY KEY NOT NULL,
	`document_object_key` text,
	`document_original_name` text,
	`document_page_count` integer,
	`document_size_bytes` integer,
	`document_status` text,
	`document_error` text,
	`recipient_display_value` text,
	`recipient_e164` text,
	`quote_amount` text,
	`quote_currency` text,
	`payment_status` text,
	`checkout_url` text,
	`fax_status` text,
	`fax_pages_sent` integer,
	`fax_pages_submitted` integer,
	`fax_error` text,
	`delivery_attempt` integer DEFAULT 0 NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "fax_session_singleton" CHECK (`id` = 1),
	CONSTRAINT "fax_session_document_status" CHECK (`document_status` IS NULL OR `document_status` IN ('processing', 'ready', 'failed')),
	CONSTRAINT "fax_session_document_error" CHECK (`document_error` IS NULL OR `document_error` IN ('ENCRYPTED_PDF', 'EMPTY_PDF', 'FILE_TOO_LARGE', 'INVALID_FILE_TYPE', 'INVALID_PDF', 'TOO_MANY_PAGES', 'PROCESSING_FAILED')),
	CONSTRAINT "fax_session_document_status_consistency" CHECK ((`document_status` = 'failed' AND `document_error` IS NOT NULL) OR (`document_status` IS NULL OR `document_status` != 'failed') AND `document_error` IS NULL),
	CONSTRAINT "fax_session_quote_currency" CHECK (`quote_currency` IS NULL OR `quote_currency` = 'ILS'),
	CONSTRAINT "fax_session_payment_status" CHECK (`payment_status` IS NULL OR `payment_status` IN ('initiated', 'pending', 'paid', 'failed')),
	CONSTRAINT "fax_session_fax_status" CHECK (`fax_status` IS NULL OR `fax_status` IN ('preparing', 'queued', 'sending', 'finalizing', 'service_delayed', 'delivered', 'failed')),
	CONSTRAINT "fax_session_fax_pages_sent" CHECK (`fax_pages_sent` IS NULL OR `fax_pages_sent` >= 0),
	CONSTRAINT "fax_session_fax_pages_submitted" CHECK (`fax_pages_submitted` IS NULL OR `fax_pages_submitted` >= 0),
	CONSTRAINT "fax_session_fax_page_progress" CHECK (`fax_pages_sent` IS NULL OR `fax_pages_submitted` IS NULL OR `fax_pages_sent` <= `fax_pages_submitted`),
	CONSTRAINT "fax_session_delivery_attempt" CHECK (`delivery_attempt` >= 0),
	CONSTRAINT "fax_session_fax_error" CHECK (`fax_error` IS NULL OR `fax_error` IN ('BUSY', 'CALL_REJECTED', 'CANCELED', 'CONNECTION_FAILED', 'DELIVERY_UNCONFIRMED', 'DESTINATION_UNAVAILABLE', 'DOCUMENT_PROCESSING_FAILED', 'FAX_INCOMPATIBLE', 'INVALID_NUMBER', 'NO_ANSWER', 'PARTIAL_TRANSMISSION', 'ROUTE_UNAVAILABLE', 'SERVICE_UNAVAILABLE', 'TRANSMISSION_INTERRUPTED', 'UNKNOWN_FAILURE', 'VOICE_ANSWERED'))
);
